export enum PropertyType {
  APARTMENT = "APARTMENT",
  HOUSE = "HOUSE",
  CONDO = "CONDO",
  TOWNHOUSE = "TOWNHOUSE",
  STUDIO = "STUDIO",
}

export enum PropertyStatus {
  VACANT = "VACANT",
  LISTED = "LISTED",
  OCCUPIED = "OCCUPIED",
  MAINTENANCE = "MAINTENANCE",
}

export enum LeaseStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  TERMINATED = "TERMINATED",
}

export enum PaymentStatus {
  UPCOMING = "UPCOMING",
  PENDING = "PENDING",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
}

export enum MaintenancePriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  EMERGENCY = "EMERGENCY",
}

export enum MaintenanceStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export enum MaintenanceCategory {
  PLUMBING = "PLUMBING",
  ELECTRICAL = "ELECTRICAL",
  HVAC = "HVAC",
  APPLIANCE = "APPLIANCE",
  STRUCTURAL = "STRUCTURAL",
  PEST_CONTROL = "PEST_CONTROL",
  OTHER = "OTHER",
}

export enum DocumentFolder {
  IDENTIFICATION = "IDENTIFICATION",
  LEASE_AGREEMENTS = "LEASE_AGREEMENTS",
  SIGNED_DOCUMENTS = "SIGNED_DOCUMENTS",
  INSPECTION_REPORTS = "INSPECTION_REPORTS",
  INSURANCE = "INSURANCE",
  OTHER = "OTHER",
}

export enum DocumentRequestType {
  PROOF_OF_ADDRESS = "PROOF_OF_ADDRESS",
  PROOF_OF_IDENTITY = "PROOF_OF_IDENTITY",
  SIGNED_LEASE = "SIGNED_LEASE",
  MOVE_IN_CHECKLIST = "MOVE_IN_CHECKLIST",
}

export enum TenantStatus {
  INVITED = "INVITED",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum OnboardingStatus {
  NEW = "NEW",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  PHONE_VERIFIED = "PHONE_VERIFIED",
  PASSWORD_SET = "PASSWORD_SET",
  ONBOARDED = "ONBOARDED",
}

export enum ManagerRole {
  ADMIN = "ADMIN",
  AGENT = "AGENT",
}

export enum NotificationType {
  INFO = "INFO",
  ACTION = "ACTION",
}

export enum ActionType {
  SIGN_DOCUMENT = "SIGN_DOCUMENT",
  SIGN_LEASE = "SIGN_LEASE",
  UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT",
  BASIC_COMPLETE = "BASIC_COMPLETE",
  MAINTENANCE_UPDATE = "MAINTENANCE_UPDATE",
  LEASE_EXPIRY = "LEASE_EXPIRY",
  RENT_REMINDER = "RENT_REMINDER",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  PAYMENT_OVERDUE = "PAYMENT_OVERDUE",
  INSPECTION_SCHEDULED = "INSPECTION_SCHEDULED",
  LEASE_RENEWAL = "LEASE_RENEWAL",
}

export enum DocumentRequestStatus {
  PENDING = "PENDING",
  UPLOADED = "UPLOADED",
  CANCELED = "CANCELED",
}
