-- CreateEnum
CREATE TYPE "ONBOARDING_STATUS" AS ENUM ('NEW', 'EMAIL_VERIFIED', 'PHONE_VERIFIED', 'PASSWORD_SET', 'ONBOARDED');

-- AlterTable
ALTER TABLE "clients" ADD COLUMN     "onboarding_status" "ONBOARDING_STATUS" NOT NULL DEFAULT 'NEW';
