services:
  postgres:
    container_name: leaselink-pg
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaselink
      PG_DATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
